/**
 * Security and caching headers for every prerendered page and asset, written
 * to the build's `_headers` file, which Cloudflare applies to static assets.
 * The on-demand pages (/contact, /api/contact) get the same security headers
 * from src/middleware.ts. The policy itself lives in src/lib/security-policy.ts.
 *
 * Inline scripts are allowed by SHA-256 hash, collected from the built pages.
 * HTML keeps Cloudflare's default caching (revalidated on every request).
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';
import {
  contentSecurityPolicy,
  inlineScripts,
  scriptHash,
  SECURITY_HEADERS,
} from '../lib/security-policy';

const YEAR = 'public, max-age=31536000, immutable';
/** Not content-hashed (regenerated under the same name), so not immutable. */
const MONTH = 'public, max-age=2592000, stale-while-revalidate=86400';

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) return walk(path);
    return name.endsWith('.html') ? [path] : [];
  });
}

export function securityHeaders(): AstroIntegration {
  return {
    name: 'monolith-security-headers',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const out = fileURLToPath(dir);
        const bodies = new Set(
          walk(out).flatMap((file) => inlineScripts(readFileSync(file, 'utf8'))),
        );
        const hashes = await Promise.all([...bodies].map(scriptHash));
        const security = Object.entries({
          'Content-Security-Policy': contentSecurityPolicy(hashes),
          ...SECURITY_HEADERS,
        });
        const rule = (path: string, headers: [string, string][]) =>
          `${path}\n${headers.map(([key, value]) => `  ${key}: ${value}`).join('\n')}`;
        // Cloudflare builds of any other branch are previews: keep them out of search.
        const branch = process.env.WORKERS_CI_BRANCH ?? process.env.CF_PAGES_BRANCH;
        const preview =
          branch !== undefined && branch !== (process.env.PRODUCTION_BRANCH || 'main');
        const file = [
          '# Generated by src/integrations/security-headers.ts at build time. Do not edit.',
          rule('/*', preview ? [...security, ['X-Robots-Tag', 'noindex']] : security),
          rule('/_astro/*', [['Cache-Control', YEAR]]),
          rule('/fonts/*', [['Cache-Control', YEAR]]),
          ...['posters', 'textures', 'og', 'media', 'models'].map((folder) =>
            rule(`/${folder}/*`, [['Cache-Control', MONTH]]),
          ),
          ...[
            '/favicon.ico',
            '/favicon.svg',
            '/apple-touch-icon.png',
            '/icon-192.png',
            '/icon-512.png',
            '/icon-maskable-512.png',
          ].map((path) => rule(path, [['Cache-Control', MONTH]])),
        ].join('\n\n');
        writeFileSync(join(out, '_headers'), `${file}\n`);
        logger.info(`_headers written (${hashes.length} inline script hashes).`);
      },
    },
  };
}
